export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const ADDED_EMPLOYEE = "ADDED_EMPLOYEE";

export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const UPDATED_EMPLOYEE = "UPDATED_EMPLOYEE";

export const DELET_EMPLOYEE = "DELET_EMPLOYEE";
export const DELETED_EMPLOYEE = "DELETED_EMPLOYEE";

export const GET_EMPLOYEE_LIST = "GET_EMPLOYEE_LIST";
export const GOT_EMPLOYEE_LIST = "GOT_EMPLOYEE_LIST";

export const RESET_STORE = 'RESET_STORE';
export const RESETED_STORE = 'RESETED_STORE'; 